Point snapshot-master at sibelius2 instead
The archive.d.o vhost took over the primary IP, causing backups to fail:

Subject: Cron <debbackup@storace> cd /srv/backups/git-backup && for i in *.git; do (cd $i && flock . -c 'git fetch --all --quiet'  ); done

fatal: repository 'http://snapshot-master.debian.org/gits/snapshot-dumps.git/' not found
error: Could not fetch origin